site_name: docker-transmission-openvpn
site_url: http://haugene.github.io/docker-transmission-openvpn/
repo_url: https://github.com/haugene/docker-transmission-openvpn/
theme:
  name: 'material'
markdown_extensions:
    - toc:
        permalink: True
        separator: "_"
nav:
   - 'Home': 'index.md'
   - 'Run from Docker registry': 'run-from-docker-registry.md'
   - 'Supported providers': 'supported-providers.md'
   - 'Arguments': 'arguments.md'
   - 'Custom pre/post scripts': 'custom-scripts.md'
   - 'RSS plugin': 'rss-plugin.md'
   - 'Use docker env file': 'dockerenv.md'
   - 'Access': 'access.md'
   - 'Running on ARM': 'run-on-arm.md'
   - 'NORDVPN update script': 'nordvpn-script.md'
   - 'Synology NAS': 'synology-nas.md'
   - 'Systemd integration': 'systemd-integration.md'
   - 'Known issues, tips and tricks': 'known-issues.md'
plugins:
    - search