FROM balenalib/raspberrypi3:stretch

RUN apt-get update \
      && apt-get install -y \
        ca-certificates \
        nginx \
      && rm -rf /var/lib/apt/lists/*

RUN ln -sf /dev/stdout /var/log/nginx/access.log \
      && ln -sf /dev/stderr /var/log/nginx/error.log

EXPOSE 8080

COPY nginx.conf /etc/nginx/nginx.conf

CMD ["nginx", "-g", "daemon off;"]
