#!/bin/bash
# Source our persisted env variables from container startup
. /etc/transmission/environment-variables.sh
source /etc/openvpn/utils.sh

# Update config status to success.
CONFIG_STATUS=$(sed -n "s/^; status \(.*\)/\1/p" "${CONFIG}")
if [[ -n "${CONFIG_STATUS}" ]]; then
  CONFIG_STATUS="success"
  sed -i "/^; status.*$/d" "${CONFIG}"
  sed -i "\$q" "${CONFIG}" # Ensure config ends with a line feed
  echo "; status ${CONFIG_STATUS}" >> "${CONFIG}"
fi

if [[ "${OVERRIDE_DNS_ACTIVE,,}" == "true" ]]; then
  echo "DNS: OVERRIDE_DNS is set, skipping VPN DNS update"
else
  NS=
  NS_ROUTES=( )
  DOMAIN=
  SEARCH=
  i=1
  while true; do
    foreign_opt_var="foreign_option_${i}"
    opt="${!foreign_opt_var}"
    [ -z "${opt}" ] && break
    if [ "${opt}" != "${opt#dhcp-option DOMAIN *}" ]; then
      if [ -z "${DOMAIN}" ]; then
        DOMAIN="${opt#dhcp-option DOMAIN *}"
      else
        SEARCH="${SEARCH}${SEARCH:+ }${opt#dhcp-option DOMAIN *}"
      fi
    elif [ "${opt}" != "${opt#dhcp-option DNS *}" ]; then
      new_ns="${opt#dhcp-option DNS *}"
      NS_ROUTES+=( "${new_ns}" )
      NS="${NS}nameserver ${new_ns}\n"
    fi
    i=$((${i} + 1))
  done
  if [ -n "${NS}" ]; then
    for r in "${NS_ROUTES[@]}"; do
      ip route replace "$r" dev "${dev}"
    done
    DNS="# Generated by openvpn for interface ${dev}\n"
    if [ -n "${SEARCH}" ]; then
      DNS="${DNS}search ${DOMAIN} ${SEARCH}\n"
    elif [ -n "${DOMAIN}" ]; then
      DNS="${DNS}domain ${DOMAIN}\n"
    fi
    DNS="${DNS}${NS}"
    if [ -e /etc/resolv.conf ] && [ ! -e /etc/resolv.conf.sv ]; then
      cp /etc/resolv.conf /etc/resolv.conf.sv
    fi
    printf '%b' "$DNS" > /etc/resolv.conf
    chmod 644 /etc/resolv.conf
    echo "DNS: updated /etc/resolv.conf with VPN-provided DNS"
  else
    echo "DNS: no DNS options received from VPN server"
  fi
fi

/etc/transmission/start.sh
[[ -f /opt/privoxy/start.sh && -x /opt/privoxy/start.sh ]] && /opt/privoxy/start.sh

exit 0
