name: Transmission Version Check

on:
  schedule:
    - cron: 0 * * * *
  workflow_dispatch: {}

jobs:
  get-transmission-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: dev

      - name: Check for new version of Transmission
        run: |
          LATEST_VERSION=$(curl -L https://api.github.com/repos/transmission/transmission/releases/latest | grep tag_name | awk '{print $2}' | sed -e 's/"//g' -e 's/,//')
          CURRENT_VERSION=$(cat upstream/transmission-version.txt)
          if [ "$LATEST_VERSION" != "$CURRENT_VERSION" ]; then
            echo "$LATEST_VERSION" > upstream/transmission-version.txt
            git config --global user.email "workflow@github.com"
            git config --global user.name "workflow runner"
            git add upstream/transmission-version.txt
            git config user.email "transmission-bot@users.noreply.github.com"
            git config user.name "Transmission-Bot"
            git commit -m "update transmission build version to ${LATEST_VERSION}"
            git push origin dev
          fi
